### ISSUE TITLE
Needs seperate field for github enterprise access token

### ISSUE THREAD

**Issue by hipstersmoothie** [bfred-it/github-issue-link-status#14]
I want this plugin to work both on enterprise and public github. So there needs to be two input, 1 for public github access token, and 1 for enterprise github access token.

Or there needs to be a way to define an access token for a location.

**Comment by fregante** [comment]
That’s a good point. Unfortunately this seems pretty complex since, if someone has more than one Enterprise site, we’d need multiple fields paired with their domain.

I’m wondering if this can be handled by the permission module somehow, combined with options-sync. 

The alternative would be **to clone the extension locally and setting the custom domain in the manifest.json**. 

This is a problem that all GitHub extensions have, so it’d be great to find a solution common to all.

**Comment by fregante** [comment]
I opened a request here: https://github.com/sindresorhus/module-requests/issues/114

**Comment by fregante** [comment]
If anyone wants to submit a PR, you can copy Refined GitHub's solution: https://github.com/sindresorhus/refined-github/pull/2293

The latest version of that code is at https://github.com/sindresorhus/refined-github/blob/master/source/options-storage.ts
