### ISSUE TITLE
Strip whitespace when pasting access token

### ISSUE THREAD

**Issue by mlissner** [bfred-it/github-issue-link-status#19]
I just started using the extension and my first step was to add my github token. I copied it from the website then pasted it in, but the box was red! Eventually I figured out it was red because I had a space at the front of the thing I copied that I accidentally pasted in. This was hard to figure out because the space just looked like padding at first.

Then, once I figured out that the space was extra, I realized that the last character of my token had been stripped because of the max length attribute on the input field, so I had to go grab that. Finally, the box was green.

Tricky business.

**Comment by fregante** [comment]
I feel the pain. Thanks for the report. 

Do you know any lightweight solutions to that? Maybe just a `paste` handler that changes the content before pasting  🤔

**Comment by mlissner** [comment]
That'd be my guess. Seems like there are some decent approaches. Here's a jquery snippet: https://stackoverflow.com/a/32809954/64911

**Comment by mlissner** [comment]
I wonder if the max length attribute is helping or hurting too. What good does it do?

**Comment by fregante** [comment]
You may be right about the `maxlength`. I just remembered that GitHub does offer a plain one-click-to-copy button so the issue shouldn't ever happen 😅

**Comment by fregante** [comment]
Would you be able to send a PR?

**Comment by mlissner** [comment]
Sorry. I wish I could, but I'm in the trenches and under water on my own work for the foreseeable future. It's a sad state.

**Comment by grahamperrin** [comment]
This bugged me, too. My first thought was that there might be white space but it looked as if there was no leading space. Invisible, I guess, due to proportional spacing. 

As a temporary improvement, maybe use a mono-space font for what's pasted? (Is that possible.)

Also maybe enhance the hint on entry, 

> Please match the requested format.

– to hint that the format requires no leading or trailing space. 

(Without a stated requirement, my first guess that was that the string should have been broken into chunks, dash-separated. A wrong guess.)

**Comment by grahamperrin** [comment]
> … GitHub does offer a plain one-click-to-copy button … 

I saw that, and tried it before anything else, but IIRC it wasn't effective. (Using Waterfox Classic here.)
