### ISSUE TITLE
provide the extensions capabilities on a different website

### ISSUE THREAD

**Issue by staabm** [bfred-it/github-issue-link-status#30]
thanks for this great tool, love to use it <3.

while using it on github I had the following idea:

would it be possible to provide the same feature set the extension already has on other websites or web-based tools?
e.g. we use jira on a local instance in which we have links to github.com pull requests, which look like:

![grafik](https://user-images.githubusercontent.com/120441/78871784-85d84a80-7a48-11ea-9dc6-accadb8e73c4.png)

couldnt the extension also color this link and provide me the same information as if this link is used on github.com?

I guess this would need some kind of whitelist in the browser extension, so it knows in which websites it should analyse

**Comment by fregante** [comment]
I think this should already work. Follow the instructions for GitHub Enterprise, it's the same concept.

**Comment by staabm** [comment]
Cool, will try. Where can I find those instructions?

This repo doesnt have a wiki, website or docs folder?

**Comment by fregante** [comment]
It’s all in the readme and options page.  

But it won’t work, the extension will only work on GitHub sites due to the selector. If I changed that it might break some things on GitHub

**Comment by staabm** [comment]
> It’s all in the readme and options page.

Hmmm

![6A6C8B1D-9CC9-4548-BCE0-C32FE826F052](https://user-images.githubusercontent.com/120441/79068787-c5fa3000-7cc9-11ea-8607-2229ab4025fe.jpeg)


With „options page“ you mean the extension settings after the extension is installed in the browser?

**Comment by staabm** [comment]
> But it won’t work, the extension will only work on GitHub sites due to the selector. If I changed that it might break some things GitHub sites 


Maybe it could work when the extension would allow to define additional selectors on a per domain basis?

**Comment by fregante** [comment]
It doesn't need any options, only 2 changes:

- automatically simplify the selector when it's not a GitHub site (detectable via `select.exist([property="og:site_name"][content="GitHub"])` or something like that)

https://github.com/fregante/github-issue-link-status/blob/48a5246e3c4deecec08a374b340d8cab8d2bf78a/source/github-issue-link-status.js#L73-L82

- group detected links by hostname and figure out the API endpoint from the `link.hostname`, instead of `location.hostname`

https://github.com/fregante/github-issue-link-status/blob/48a5246e3c4deecec08a374b340d8cab8d2bf78a/source/github-issue-link-status.js#L6

PR welcome, I won't be adding it
